export default {
    BASIC_ACTION: 'BASIC_ACTION',
    GET_NEW_PRODUCT: 'GET_NEW_PRODUCT',
    GOT_NEW_PRODUCT: 'GOT_NEW_PRODUCT',
    GOT_NEW_PRODUCT_ERROR_FALLBACK: 'GOT_NEW_PRODUCT_ERROR_FALLBACK'
}